##
##  makefile for creating a photo gallery
##

all:  index.html

index.html: Section10 Section20 Section80
	./CreateIndex.ksh -f


clean:
	rm -f *~
	rm -f #*



##
##  depends
##

index.html:  Section10 Section20 Section80
